language: java

jdk:
  - oraclejdk8
before_install:
 cd tpa #solo si no tienen el pom en el raíz del repositorio
 
notifications:
  email:
    recipients:
      - gastonprietoutn@gmail.com
      - juanignaciosierra96@gmail.com
